version: '3'

networks:
  network:

volumes:
  incoming-data-records:

services:
  backend:
    build: ./backend
    container_name: mobilecs-backend
    image: mobilecs-backend
    volumes:
      - incoming-data-records:/mobilecs/incoming-data-records
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: mobilecs-cassandra
      KAFKA_BOOTSTRAP_SERVERS: mobilecs-kafka:29092
      MOBILECS_INCOMING_DATA_RECORDS_DIR: /mobilecs/incoming-data-records
    networks:
      - network
    depends_on:
      - cassandra

  cassandra:
    container_name: mobilecs-cassandra
    image: cassandra:3.11.8
    ports:
    - "9042:9042"
    networks:
    - network

  zookeeper:
    container_name: mobilecs-zookeeper
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - network

  kafka:
    container_name: mobilecs-kafka
    image: confluentinc/cp-kafka:5.4.3
    ports:
    - "9092:9092"
    - "29092:29092"
    expose:
    - "9092"
    - "29092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://mobilecs-kafka:29092,LOCAL_DOCKER://mobilecs-kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mobilecs-kafka:29092,LOCAL_DOCKER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,LOCAL_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: -1
    networks:
    - network
    depends_on:
      - zookeeper

  jobmanager:
    build: ./flink
    container_name: mobilecs-jobmanager
    image: mobilecs-flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment: 
      INITIAL_JOBS: >
        com.hclc.mobilecs.flink.importing.IncomingDataRecordsImporter;flink-0.0.1-SNAPSHOT.jar
        com.hclc.mobilecs.flink.ingesting.IncomingDataRecordsIngester;flink-0.0.1-SNAPSHOT.jar
      INITIAL_JOBS_DIR: /mobilecs/flink-jobs
      INITIAL_JOBS_DELAY: 10
      INITIAL_JOBS_PERIOD: 5
      INITIAL_JOBS_JOBMANAGER: localhost:8081
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: mobilecs-jobmanager
      CASSANDRA_CONTACT_POINT: mobilecs-cassandra
      KAFKA_BOOTSTRAP_SERVERS: mobilecs-kafka:29092
      MOBILECS_INCOMING_DATA_RECORDS_DIR: /mobilecs/incoming-data-records
    networks:
      - network

  taskmanager:
    container_name: mobilecs-taskmanager
    image: flink:1.11.2-scala_2.11
    volumes:
      - incoming-data-records:/mobilecs/incoming-data-records
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: mobilecs-jobmanager
        taskmanager.numberOfTaskSlots: 2
      CASSANDRA_CONTACT_POINT: mobilecs-cassandra
      KAFKA_BOOTSTRAP_SERVERS: mobilecs-kafka:29092
      MOBILECS_INCOMING_DATA_RECORDS_DIR: /mobilecs/incoming-data-records
    networks:
      - network
    depends_on:
      - jobmanager