spring:
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: mobilecs

kafka:
  bootstrap-servers: localhost:9092
  client-id: mobilecs-backend

management:
  endpoint:
    health:
      probes:
        # enable liveness and readiness probes
        enabled: true

mobilecs:
  incoming-data-records-dir: /tmp/incoming-data-records
  generator:
    msisdns-batch-size: 1
    incoming-data-records-months: 1