spring:
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: mobilecs

management:
  endpoint:
    health:
      probes:
        # enable liveness and readiness probes
        enabled: true
