apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilecs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilecs
  strategy: {}
  template:
    metadata:
      labels:
        app: mobilecs
    spec:
      containers:
      - name: mobilecs
        image: bkaminnski/mobilecs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_CASSANDRA_CONTACT_POINTS
          value: "cassandra-service"
        - name: SPRING_DATA_CASSANDRA_PORT
          value: "9042"
        resources:
          requests:
            memory: "250Mi"
            # cpu: "250m"
          limits:
            memory: "500Mi"
            # cpu: "500m"
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mobilecs-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: mobilecs
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-single-node-pv
  labels:
    type: local
spec:
  storageClassName: cassandra-single-node
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: "/data/cassandra-single-node/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-single-node-pvc
spec:
  storageClassName: cassandra-single-node
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
      # cpu: "500m"
    limits:
      storage: 500Mi
      # cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy: {}
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.11.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9042
        volumeMounts:
        - name: cassandra-volume
          mountPath: /var/lib/cassandra
        env:
        - name: MAX_HEAP_SIZE
          value: "500M"
        - name: HEAP_NEWSIZE
          value: "100M"
        resources:
          requests:
            memory: "750Mi"
            # cpu: "500m"
          limits:
            memory: "750Mi"
            # cpu: "500m"
      volumes:
      - name: cassandra-volume
        persistentVolumeClaim:
          claimName: cassandra-single-node-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  ports:
  - name: "9042"
    port: 9042
    targetPort: 9042
  selector:
    app: cassandra
